#!/usr/bin/env bash

#Creates a file, Prints to infinity and beyond indefinitely
#diplays I hate the kill command when receiving a SIGTERM signal
#Deletes the file created and terminaes itself  when receiving a SIGQUIT or
#SIGTERM signal

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

dont_kill_me()
{
echo "I hate the kill command"
sudo rm /var/run/myscript.pid
}

trap 'dont_kill_me; exit' SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
while :; do echo 'To infinity and beyond'; sleep 2; done
