#!/usr/bin/env bash
# A script for printing "Best School" 10 times
# with the 9th iteration printing "Hi" followed by "Best School".
i="0"
while [ $i -lt 10 ]
do
echo "Best School"
if [ $i -eq 8 ]
then echo "Hi"
fi
i=$((i+1))
done

